import Head from "next/head";

import Header from "@/components/Common/Header";
import DreamUniversity from "@/components/Common/DreamUniversity";
import Testimonials from "@/components/Common/Testimonials";
import Footer from "@/components/Common/Footer";

import AboutBanner from "@/components/AboutPageComponents/Banner";
import AboutDetails from "@/components/AboutPageComponents/Details";
import OurStory from "@/components/AboutPageComponents/OurStory";
import Leadership from "@/components/AboutPageComponents/Leadership";
import OurTeam from "@/components/AboutPageComponents/OurTeaam";

export default function Home() {
  return (
    <>
      <Head>
        <title>About Us - Unireach</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <AboutBanner />
      <AboutDetails />
      <OurStory />
      <Leadership />
      <OurTeam />
      <Testimonials />
      <DreamUniversity />
      <Footer />
    </>
  );
}
