import Head from "next/head";

import Header from "@/components/Common/Header";
import Footer from "@/components/Common/Footer";

import ContactBanner from "@/components/ContactPageComponents/Banner";
import ContactDetails from "@/components/ContactPageComponents/ContactDetails";

export default function Home() {
  return (
    <>
      <Head>
        <title>Contact Us - Unireach</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <ContactBanner />
      <ContactDetails />
      <Footer />
    </>
  );
}
