import Head from "next/head";

import Header from "@/components/Common/Header";
import OurPlacements from "@/components/Common/OurPlacements";
import DreamUniversity from "@/components/Common/DreamUniversity";
import Testimonials from "@/components/Common/Testimonials";
import Footer from "@/components/Common/Footer";

import HomeBanner from "@/components/HomePageComponents/banner";
import AboutSection from "@/components/HomePageComponents/AboutSection";
import WhyUs from "@/components/HomePageComponents/WhyUs";
import OurService from "@/components/HomePageComponents/OurService";

export default function Home({
  pageData,
  placementsData,
  testimonialData,
  optionPageData,
}) {
  console.log(optionPageData);
  return (
    <>
      <Head>
        <title>Home - Unireach</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header headerOption={optionPageData.acf} />
      <HomeBanner bannerData={pageData.banner} />
      <AboutSection aboutData={pageData.about_us} />
      <WhyUs whyUsData={pageData.why_us} />
      <OurService OurServiceData={pageData.our_service} />
      <OurPlacements placementsData={placementsData} /> {/* Pass the data */}
      <Testimonials testimonialData={testimonialData} /> {/* Pass the data */}
      <DreamUniversity optionData={optionPageData.acf} />
      <Footer footerOption={optionPageData.acf} />
    </>
  );
}

export const getStaticProps = async () => {
  try {
    const apiData = `https://unireach.in/wp-json/wp/v2/pages/7`;
    const optionData = `https://unireach.in/wp-json/acf/v3/options/option`;

    const responsePageData = await fetch(apiData);
    const PageData = await responsePageData.json();

    const responseOptionPageData = await fetch(optionData);
    const optionPageData = await responseOptionPageData.json();

    const acf = PageData?.acf;

    if (acf) {
      const fetchImageUrl = async (imageId) => {
        try {
          const response = await fetch(
            `https://unireach.in/wp-json/wp/v2/media/${imageId}`
          );
          const imageData = await response.json();
          return imageData.source_url;
        } catch (error) {
          console.error(`Error fetching image data for ID ${imageId}:`, error);
          return null;
        }
      };

      const replaceImageIdsWithUrls = async (data, parentKey = "") => {
        for (const key in data) {
          if (data.hasOwnProperty(key)) {
            const currentKey = parentKey ? `${parentKey}.${key}` : key;
            if (typeof data[key] === "number") {
              const imageUrl = await fetchImageUrl(data[key]);
              if (imageUrl) {
                console.log(
                  `Replacing image ID ${data[key]} at ${currentKey} with URL ${imageUrl}`
                );
                data[key] = imageUrl;
              } else {
                console.warn(
                  `Failed to fetch URL for image ID ${data[key]} at ${currentKey}`
                );
              }
            } else if (typeof data[key] === "object" && data[key] !== null) {
              await replaceImageIdsWithUrls(data[key], currentKey);
            }
          }
        }
      };

      await replaceImageIdsWithUrls(acf);
    } else {
      console.warn("No ACF data found in PageData");
    }

    // Fetch OurPlacements CPT data
    const placementsRes = await fetch(
      `https://unireach.in/wp-json/wp/v2/our_placements?per_page=100`
    );
    const placementsData = await placementsRes.json();

    // Fetch Testimonials CPT data
    const testimonialRes = await fetch(
      `https://unireach.in/wp-json/wp/v2/testimonial?per_page=100`
    );
    const testimonialData = await testimonialRes.json();

    return {
      props: {
        pageData: acf,
        optionPageData,
        placementsData,
        testimonialData,
      },
      revalidate: 30,
    };
  } catch (error) {
    console.error("Error fetching page data:", error);
    return {
      notFound: true,
    };
  }
};
