import Head from "next/head";

import Header from "@/components/Common/Header";
import OurPlacements from "@/components/Common/OurPlacements";
import DreamUniversity from "@/components/Common/DreamUniversity";
import Testimonials from "@/components/Common/Testimonials";
import Footer from "@/components/Common/Footer";

import HomeBanner from "@/components/HomePageComponents/banner";
import AboutSection from "@/components/HomePageComponents/AboutSection";
import WhyUs from "@/components/HomePageComponents/WhyUs";
import OurService from "@/components/HomePageComponents/OurService";

export default function Home({ pageData }) {
  console.log(pageData);
  return (
    <>
      <Head>
        <title>Home - Unireach</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <HomeBanner bannerData={pageData.banner} />
      <AboutSection aboutData={pageData.about_us} />
      <WhyUs whyUsData={pageData.why_us} />
      <OurService />
      <OurPlacements />
      <Testimonials />
      <DreamUniversity />
      <Footer />
    </>
  );
}

export const getStaticProps = async () => {
  try {
    const apiData = `https://unireach.in/wp-json/wp/v2/pages/7`;
    const responsePageData = await fetch(apiData);
    const PageData = await responsePageData.json();

    return {
      props: {
        pageData: PageData?.acf,
      },
      revalidate: 30,
    };
  } catch (error) {
    console.error("Error fetching WooCommerce products:", error);
    return {
      notFound: true,
    };
  }
};
