import Head from "next/head";

import Header from "@/components/Common/Header";
import OurPlacements from "@/components/Common/OurPlacements";
import DreamUniversity from "@/components/Common/DreamUniversity";
import Testimonials from "@/components/Common/Testimonials";
import Footer from "@/components/Common/Footer";

import HomeBanner from "@/components/HomePageComponents/banner";
import AboutSection from "@/components/HomePageComponents/AboutSection";
import WhyUs from "@/components/HomePageComponents/WhyUs";
import OurService from "@/components/HomePageComponents/OurService";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Unireach</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <HomeBanner />
      <AboutSection />
      <WhyUs />
      <OurService />
      <OurPlacements />
      <Testimonials />
      <DreamUniversity />
      <Footer />
    </>
  );
}
