import Head from "next/head";

import Header from "@/components/Common/Header";
import DreamUniversity from "@/components/Common/DreamUniversity";
import Footer from "@/components/Common/Footer";

import ServiceBanner from "@/components/ServicePageComponents/Banner";
import ServiceSection from "@/components/ServicePageComponents/ServiceSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Services - Unireach</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <ServiceBanner />
      <ServiceSection />
      <DreamUniversity />
      <Footer />
    </>
  );
}
