import Head from "next/head";

import Header from "@/components/Common/Header";
import DreamUniversity from "@/components/Common/DreamUniversity";
import Testimonials from "@/components/Common/Testimonials";
import Footer from "@/components/Common/Footer";

import WhyUsBanner from "@/components/WhyUsPageComponents/Banner";
import WhyUsDetails from "@/components/WhyUsPageComponents/WhyUsDetails";

export default function Home() {
  return (
    <>
      <Head>
        <title>Why Us - Unireach</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <WhyUsBanner />
      <WhyUsDetails />
      <Testimonials />
      <DreamUniversity />
      <Footer />
    </>
  );
}
